# Generated by Django 2.2.2 on 2019-09-16 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_about_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='imagen',
            field=models.FileField(upload_to='perfil', verbose_name='Imagen de Perfil: '),
        ),
    ]
